build_linux:
  stage: build
  image: electronuserland/builder:latest
  script:
    - |
      echo GIT_BRANCH="$CI_COMMIT_REF_NAME" > electron-builder.env
      sha=$CI_COMMIT_SHORT_SHA commithash="${sha:0:5}"
      sed -i -re "s#[\"]version[\"]: [\"](.*)[\"]#\"version\": \"\1-$commithash\"#" package.json
      npm install --no-audit
      npm run build-native-linux
  artifacts:
    name: "BLOCKDX-$CI_COMMIT_REF_NAME-linux"
    paths:
      - dist-native/*.tar.gz
      - dist-native/*.AppImage
      - dist-native/*.deb

build_win:
  stage: build
  image: electronuserland/builder:wine
  script:
    - |
      echo GIT_BRANCH="$CI_COMMIT_REF_NAME" > electron-builder.env
      sha=$CI_COMMIT_SHORT_SHA commithash="${sha:0:5}"
      sed -i -re "s#[\"]version[\"]: [\"](.*)[\"]#\"version\": \"\1-$commithash\"#" package.json
      npm install --no-audit
      npm run build-native-win
  artifacts:
    name: "BLOCKDX-$CI_COMMIT_REF_NAME-win"
    paths:
      - dist-native/*.exe
      - dist-native/*.zip

build_mac:
  stage: build
  image: blocknetdx/devbuilds:blockdx-gitlab-mac
  script:
    - |
      echo GIT_BRANCH="$CI_COMMIT_REF_NAME" > electron-builder.env
      sha=$CI_COMMIT_SHORT_SHA commithash="${sha:0:5}"
      sed -i -re "s#[\"]version[\"]: [\"](.*)[\"]#\"version\": \"\1-$commithash\"#" package.json
      npm install --no-audit
      npm run build-native-mac
  artifacts:
    name: "BLOCKDX-$CI_COMMIT_REF_NAME-mac"
    paths:
      - dist-native/mac/BLOCK DX.app

test_artifacts:
  stage: test
  image: ubuntu:bionic
  script:
    - "set -- dist-native/BLOCK-DX-*-linux-x64.tar.gz && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-linux-x86_64.AppImage && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-linux-armv7l.AppImage && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-linux-amd64.deb && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-win.exe && [[ -f \"$1\" ]]"
    - "set -- dist-native/BLOCK-DX-*-win-x64.zip && [[ -f \"$1\" ]]"
    - "set -- dist-native/mac/BLOCK*DX.app && [[ -d \"$1\" ]]"
